# Copyright 2021-2023 Axel Huebl
#
# This file is part of ImpactX
#
# License: BSD-3-Clause-LBNL

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: docs/source/conf.py

python:
   install:
   - requirements: docs/requirements.txt

formats:
  - htmlzip
#  - pdf
#  - epub

