# Copyright 2021-2023 The ImpactX Community
#
# This file is part of ImpactX.
#
# License: BSD-3-Clause-LBNL
# Authors: Axel Huebl

name: 📜 Source

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-source
  cancel-in-progress: true

jobs:
  style:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Non-ASCII characters
      run: .github/workflows/source/hasNonASCII

    - name: TABs
      run: .github/workflows/source/hasTabs

    - name: End-of-Line whitespaces
      run: .github/workflows/source/hasEOLwhiteSpace

    - name: Doxygen
      run: |
        sudo apt-get install -y --no-install-recommends doxygen
        .github/workflows/source/doxygen
